/* export.js — PDF export via a print window.
 *
 * Opens a new window with a clean, self-contained HTML table (no shared
 * styles, so it prints identically anywhere) and triggers the browser's
 * print dialog, where the user can "Save as PDF". Rows are ordered the way
 * the rack reads on screen, honouring the numbering direction. A summary
 * row reports total devices, used U, and free U.
 */
window.Exporter = (function () {
  "use strict";

  function exportPDF() {
    var s = State.get();
    var win = window.open("", "_blank", "width=820,height=900");
    if (!win) {
      alert("Please allow pop-ups to export a PDF.");
      return;
    }
    win.document.open();
    win.document.write(buildHTML(s));
    win.document.close();
    // let layout settle, then print
    win.focus();
    win.onload = function () {
      win.print();
    };
  }

  function buildHTML(s) {
    var rows = deviceRows(s);
    var usedU = s.devices.reduce(function (sum, d) {
      return sum + d.u;
    }, 0);
    var freeU = Math.max(0, s.rack.size - usedU);

    return (
      "<!DOCTYPE html><html><head><meta charset='utf-8'><title>" +
      esc(s.projectName) +
      "</title><style>" +
      css() +
      "</style></head><body>" +
      "<header><h1>" +
      esc(s.projectName) +
      "</h1><div class='meta'>" +
      s.rack.size +
      "U rack · numbering " +
      (s.rack.direction === "top-down" ? "top → bottom" : "bottom → top") +
      " · start U" +
      s.rack.startUnit +
      "</div></header>" +
      "<table><thead><tr>" +
      "<th class='c'>U range</th><th class='c'>Size</th><th>Device</th>" +
      "<th>Brand / model</th><th class='c'>Faceplate</th>" +
      "</tr></thead><tbody>" +
      rows +
      "</tbody><tfoot><tr>" +
      "<td colspan='5'>" +
      s.devices.length +
      " device" +
      (s.devices.length === 1 ? "" : "s") +
      " · " +
      usedU +
      "U used · " +
      freeU +
      "U free of " +
      s.rack.size +
      "U" +
      "</td></tr></tfoot></table>" +
      "<footer>Generated by Open Rack Builder</footer>" +
      "</body></html>"
    );
  }

  function deviceRows(s) {
    if (!s.devices.length) {
      return "<tr><td colspan='5' class='empty'>No devices placed.</td></tr>";
    }
    // sort by on-screen reading order (top row first)
    var sorted = s.devices.slice().sort(function (a, b) {
      return a.slot - b.slot;
    });
    return sorted
      .map(function (d) {
        var top = State.displayNumber(d.slot);
        var bottom = State.displayNumber(d.slot + d.u - 1);
        var lo = Math.min(top, bottom);
        var hi = Math.max(top, bottom);
        var range = lo === hi ? "U" + lo : "U" + lo + "–" + hi;
        return (
          "<tr><td class='c'>" +
          range +
          "</td><td class='c'>" +
          d.u +
          "U</td><td>" +
          esc(d.name) +
          "</td><td>" +
          esc(d.brand || "—") +
          "</td><td class='c'><span class='swatch' style='background:" +
          esc(d.color) +
          "'></span></td></tr>"
        );
      })
      .join("");
  }

  function css() {
    return [
      "*{box-sizing:border-box}",
      "body{font:13px -apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;color:#1d1d1f;margin:40px;}",
      "header{margin-bottom:20px;}",
      "h1{font-size:20px;font-weight:600;margin:0 0 4px;}",
      ".meta{color:#86868b;font-size:12px;}",
      "table{width:100%;border-collapse:collapse;margin-top:8px;}",
      "th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #e3e3e8;font-size:12.5px;}",
      "th{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#86868b;font-weight:600;border-bottom:1px solid #c8c8d0;}",
      ".c{text-align:center;}",
      "td.c{font-variant-numeric:tabular-nums;}",
      "tfoot td{font-weight:600;border-top:2px solid #1d1d1f;border-bottom:none;padding-top:10px;}",
      ".empty{color:#86868b;text-align:center;padding:24px;}",
      ".swatch{display:inline-block;width:26px;height:14px;border-radius:3px;border:1px solid rgba(0,0,0,.25);vertical-align:middle;}",
      "footer{margin-top:24px;color:#aeaeb2;font-size:11px;}",
      "@media print{body{margin:16px;}}",
    ].join("");
  }

  function esc(str) {
    return String(str == null ? "" : str).replace(/[&<>"']/g, function (c) {
      return {
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      }[c];
    });
  }

  return { exportPDF: exportPDF };
})();
